module.exports = {
  TORRENT_NOT_EXIST  : 'TORRENT_NOT_EXIST',
  NO_STREAMABLE_FILE : 'NO_STREAMABLE_FILE',
  TOR_WATCHER_ERROR  : 'TOR_WATCHER_ERROR',
  

  MISSING_TOKEN      : 'MISSING_TOKEN',
  CORRUPTED_TOKEN    : 'CORRUPTED_TOKEN',
  EXPIRED_TOKEN      : 'EXPIRED_TOKEN',

  UNKNOWN_ERROR      : 'VOODOO_KAKEN',
  BAD_ERROR          : 'BAD_ERROR',
}