module.exports = {
  SUCCESS            : 'SUCCESS',
  FAILURE            : 'FAILURE',
  UNKNOWN_ERROR      : 'VOODOO_KAKEN',

  MAIL_ALREADY_TAKEN : 'MAIL_ALREADY_TAKEN',
  USERNAME_TAKEN     : 'USERNAME_TAKEN',

  MISSING_QUERY      : 'MISSING_QUERY',

  TORRENT_NOT_READY  : 'TORRENT_NOT_READY',
  TORRENT_NOT_EXIST  : 'TORRENT_NOT_EXIST',

}