module.exports = {
  SUCCESS            : 'SUCCESS',
  FAILURE            : 'FAILURE',
  UNKNOWN_ERROR      : 'VOODOO_KAKEN',

  INVALID_TOKEN      : 'INVALID_TOKEN',
  MAIL_NOT_VERIFIED  : 'MAIL_NOT_VERIFIED',


  MAIL_ALREADY_TAKEN : 'MAIL_ALREADY_TAKEN',
  DATA_OUT_OF_RANGE  : 'DATA_OUT_OF_RANGE',
  USERNAME_TAKEN     : 'USERNAME_TAKEN',
  CANT_CREATE_USERNAME : 'CANT_CREATE_USERNAME',

  MISSING_QUERY      : 'MISSING_QUERY',

  TORRENT_NOT_READY  : 'TORRENT_NOT_READY',
  TORRENT_NOT_EXIST  : 'TORRENT_NOT_EXIST',
  ONLY_SRT_ALLOWED   : 'ONLY_SRT_ALLOWED',
  FILE_TOO_LARGE     : 'FILE_TOO_LARGE',
  CORRUPTED_SRT_FILE : 'CORRUPTED_SRT_FILE'

}